import { asset } from "@/lib/asset";
/**
 * BrandLogo — always the official SIENA asset (crops of "SIENA logo.JPG"), never redrawn.
 * Assets are generated by scripts/build-brand-assets.mjs: crops of the master with its dark field made transparent.
 */
type Variant = "logo" | "lockup" | "symbol" | "wordmark";

const SIZES: Record<Variant, { w: number; h: number; small: number }> = {
  logo: { w: 1254, h: 1254, small: 720 },
  lockup: { w: 904, h: 850, small: 560 },
  symbol: { w: 600, h: 600, small: 160 },
  wordmark: { w: 845, h: 105, small: 420 },
};

export function BrandLogo({
  variant = "lockup", alt = "SIENA — AI Solutions & Systems", className = "", sizes = "(max-width: 700px) 70vw, 420px", priority = false, feather = true,
}: { variant?: Variant; alt?: string; className?: string; sizes?: string; priority?: boolean; feather?: boolean }) {
  const s = SIZES[variant];
  const base = asset(`/brand/siena-${variant}`);
  return (
    <picture className={`brand ${feather ? "brand--feather" : ""} ${className}`}>
      <source type="image/avif" srcSet={`${base}-${s.small}.avif ${s.small}w, ${base}.avif ${s.w}w`} sizes={sizes} />
      <source type="image/webp" srcSet={`${base}-${s.small}.webp ${s.small}w, ${base}.webp ${s.w}w`} sizes={sizes} />
      <img
        className="brand-img"
        src={`${base}.webp`}
        width={s.w}
        height={s.h}
        alt={alt}
        loading={priority ? "eager" : "lazy"}
        decoding="async"
        fetchPriority={priority ? "high" : "auto"}
      />
    </picture>
  );
}
